# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15MXdfUclk4r_eTKY9bdFJvsVIhzRe5Pu
"""

# Q1
print("This is my first program")

# Q2
print("This")
print("Is")
print("My")
print("First")
print("Program")

#Q3
x = int(input("Enter X:"))
y = int(input("Enter Y:"))
print(x + y)
print(x - y)
print(x * y )
print(x / y )
print(x // y )
print(x ** y)
print(x % y)
print(x-y*100)
print((x-y)*100)

#Q4
#Version 1:

nis_usd = 3.73
shekels = int(input("Enter the amount of NIS: "))
print(shekels / nis_usd)
print(shekels // nis_usd)

#Version 2:

usd_rate = float(input("Enter the current USD rate: "))
shekels = float(input("Enter the amount of NIS: "))
usd_val = shekels / usd_rate
print(usd_val)

#Q5
print("   #")
print("  ###")
print(" #####")
print("  ###")
print("   #")